// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: neighbors.proto

public final class Neighbors {
  private Neighbors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SquareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Square)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();

    /**
     * <code>repeated int32 values = 3;</code>
     */
    java.util.List<java.lang.Integer> getValuesList();
    /**
     * <code>repeated int32 values = 3;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated int32 values = 3;</code>
     */
    int getValues(int index);

    /**
     * <code>optional bool neighbor_left = 4;</code>
     */
    boolean getNeighborLeft();

    /**
     * <code>optional bool neighbor_right = 5;</code>
     */
    boolean getNeighborRight();

    /**
     * <code>optional bool neighbor_up = 6;</code>
     */
    boolean getNeighborUp();

    /**
     * <code>optional bool neighbor_down = 7;</code>
     */
    boolean getNeighborDown();
  }
  /**
   * Protobuf type {@code Square}
   */
  public  static final class Square extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Square)
      SquareOrBuilder {
    // Use Square.newBuilder() to construct.
    private Square(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Square() {
      x_ = 0;
      y_ = 0;
      values_ = java.util.Collections.emptyList();
      neighborLeft_ = false;
      neighborRight_ = false;
      neighborUp_ = false;
      neighborDown_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Square(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                values_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              values_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                values_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                values_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {

              neighborLeft_ = input.readBool();
              break;
            }
            case 40: {

              neighborRight_ = input.readBool();
              break;
            }
            case 48: {

              neighborUp_ = input.readBool();
              break;
            }
            case 56: {

              neighborDown_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Neighbors.internal_static_Square_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Neighbors.internal_static_Square_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Neighbors.Square.class, Neighbors.Square.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> values_;
    /**
     * <code>repeated int32 values = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated int32 values = 3;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated int32 values = 3;</code>
     */
    public int getValues(int index) {
      return values_.get(index);
    }
    private int valuesMemoizedSerializedSize = -1;

    public static final int NEIGHBOR_LEFT_FIELD_NUMBER = 4;
    private boolean neighborLeft_;
    /**
     * <code>optional bool neighbor_left = 4;</code>
     */
    public boolean getNeighborLeft() {
      return neighborLeft_;
    }

    public static final int NEIGHBOR_RIGHT_FIELD_NUMBER = 5;
    private boolean neighborRight_;
    /**
     * <code>optional bool neighbor_right = 5;</code>
     */
    public boolean getNeighborRight() {
      return neighborRight_;
    }

    public static final int NEIGHBOR_UP_FIELD_NUMBER = 6;
    private boolean neighborUp_;
    /**
     * <code>optional bool neighbor_up = 6;</code>
     */
    public boolean getNeighborUp() {
      return neighborUp_;
    }

    public static final int NEIGHBOR_DOWN_FIELD_NUMBER = 7;
    private boolean neighborDown_;
    /**
     * <code>optional bool neighbor_down = 7;</code>
     */
    public boolean getNeighborDown() {
      return neighborDown_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (getValuesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(valuesMemoizedSerializedSize);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeInt32NoTag(values_.get(i));
      }
      if (neighborLeft_ != false) {
        output.writeBool(4, neighborLeft_);
      }
      if (neighborRight_ != false) {
        output.writeBool(5, neighborRight_);
      }
      if (neighborUp_ != false) {
        output.writeBool(6, neighborUp_);
      }
      if (neighborDown_ != false) {
        output.writeBool(7, neighborDown_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(values_.get(i));
        }
        size += dataSize;
        if (!getValuesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valuesMemoizedSerializedSize = dataSize;
      }
      if (neighborLeft_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, neighborLeft_);
      }
      if (neighborRight_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, neighborRight_);
      }
      if (neighborUp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, neighborUp_);
      }
      if (neighborDown_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, neighborDown_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Neighbors.Square)) {
        return super.equals(obj);
      }
      Neighbors.Square other = (Neighbors.Square) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && getValuesList()
          .equals(other.getValuesList());
      result = result && (getNeighborLeft()
          == other.getNeighborLeft());
      result = result && (getNeighborRight()
          == other.getNeighborRight());
      result = result && (getNeighborUp()
          == other.getNeighborUp());
      result = result && (getNeighborDown()
          == other.getNeighborDown());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (37 * hash) + NEIGHBOR_LEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeighborLeft());
      hash = (37 * hash) + NEIGHBOR_RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeighborRight());
      hash = (37 * hash) + NEIGHBOR_UP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeighborUp());
      hash = (37 * hash) + NEIGHBOR_DOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeighborDown());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Neighbors.Square parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Square parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Square parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Square parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Square parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Square parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Square parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Neighbors.Square parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Square parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Square parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Neighbors.Square prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Square}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Square)
        Neighbors.SquareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Neighbors.internal_static_Square_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Neighbors.internal_static_Square_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Neighbors.Square.class, Neighbors.Square.Builder.class);
      }

      // Construct using Neighbors.Square.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        neighborLeft_ = false;

        neighborRight_ = false;

        neighborUp_ = false;

        neighborDown_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Neighbors.internal_static_Square_descriptor;
      }

      public Neighbors.Square getDefaultInstanceForType() {
        return Neighbors.Square.getDefaultInstance();
      }

      public Neighbors.Square build() {
        Neighbors.Square result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Neighbors.Square buildPartial() {
        Neighbors.Square result = new Neighbors.Square(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.x_ = x_;
        result.y_ = y_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.values_ = values_;
        result.neighborLeft_ = neighborLeft_;
        result.neighborRight_ = neighborRight_;
        result.neighborUp_ = neighborUp_;
        result.neighborDown_ = neighborDown_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Neighbors.Square) {
          return mergeFrom((Neighbors.Square)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Neighbors.Square other) {
        if (other == Neighbors.Square.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        if (other.getNeighborLeft() != false) {
          setNeighborLeft(other.getNeighborLeft());
        }
        if (other.getNeighborRight() != false) {
          setNeighborRight(other.getNeighborRight());
        }
        if (other.getNeighborUp() != false) {
          setNeighborUp(other.getNeighborUp());
        }
        if (other.getNeighborDown() != false) {
          setNeighborDown(other.getNeighborDown());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Neighbors.Square parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Neighbors.Square) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> values_ = java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = new java.util.ArrayList<java.lang.Integer>(values_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public int getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public Builder setValues(
          int index, int value) {
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public Builder addValues(int value) {
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 3;</code>
       */
      public Builder clearValues() {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private boolean neighborLeft_ ;
      /**
       * <code>optional bool neighbor_left = 4;</code>
       */
      public boolean getNeighborLeft() {
        return neighborLeft_;
      }
      /**
       * <code>optional bool neighbor_left = 4;</code>
       */
      public Builder setNeighborLeft(boolean value) {
        
        neighborLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool neighbor_left = 4;</code>
       */
      public Builder clearNeighborLeft() {
        
        neighborLeft_ = false;
        onChanged();
        return this;
      }

      private boolean neighborRight_ ;
      /**
       * <code>optional bool neighbor_right = 5;</code>
       */
      public boolean getNeighborRight() {
        return neighborRight_;
      }
      /**
       * <code>optional bool neighbor_right = 5;</code>
       */
      public Builder setNeighborRight(boolean value) {
        
        neighborRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool neighbor_right = 5;</code>
       */
      public Builder clearNeighborRight() {
        
        neighborRight_ = false;
        onChanged();
        return this;
      }

      private boolean neighborUp_ ;
      /**
       * <code>optional bool neighbor_up = 6;</code>
       */
      public boolean getNeighborUp() {
        return neighborUp_;
      }
      /**
       * <code>optional bool neighbor_up = 6;</code>
       */
      public Builder setNeighborUp(boolean value) {
        
        neighborUp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool neighbor_up = 6;</code>
       */
      public Builder clearNeighborUp() {
        
        neighborUp_ = false;
        onChanged();
        return this;
      }

      private boolean neighborDown_ ;
      /**
       * <code>optional bool neighbor_down = 7;</code>
       */
      public boolean getNeighborDown() {
        return neighborDown_;
      }
      /**
       * <code>optional bool neighbor_down = 7;</code>
       */
      public Builder setNeighborDown(boolean value) {
        
        neighborDown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool neighbor_down = 7;</code>
       */
      public Builder clearNeighborDown() {
        
        neighborDown_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Square)
    }

    // @@protoc_insertion_point(class_scope:Square)
    private static final Neighbors.Square DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Neighbors.Square();
    }

    public static Neighbors.Square getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Square>
        PARSER = new com.google.protobuf.AbstractParser<Square>() {
      public Square parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Square(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Square> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Square> getParserForType() {
      return PARSER;
    }

    public Neighbors.Square getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PuzzleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Puzzle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 size = 1;</code>
     */
    int getSize();

    /**
     * <code>repeated .Square squares = 2;</code>
     */
    java.util.List<Neighbors.Square> 
        getSquaresList();
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    Neighbors.Square getSquares(int index);
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    int getSquaresCount();
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    java.util.List<? extends Neighbors.SquareOrBuilder> 
        getSquaresOrBuilderList();
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    Neighbors.SquareOrBuilder getSquaresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Puzzle}
   */
  public  static final class Puzzle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Puzzle)
      PuzzleOrBuilder {
    // Use Puzzle.newBuilder() to construct.
    private Puzzle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Puzzle() {
      size_ = 0;
      squares_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Puzzle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                squares_ = new java.util.ArrayList<Neighbors.Square>();
                mutable_bitField0_ |= 0x00000002;
              }
              squares_.add(
                  input.readMessage(Neighbors.Square.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          squares_ = java.util.Collections.unmodifiableList(squares_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Neighbors.internal_static_Puzzle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Neighbors.internal_static_Puzzle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Neighbors.Puzzle.class, Neighbors.Puzzle.Builder.class);
    }

    private int bitField0_;
    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>optional int32 size = 1;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int SQUARES_FIELD_NUMBER = 2;
    private java.util.List<Neighbors.Square> squares_;
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    public java.util.List<Neighbors.Square> getSquaresList() {
      return squares_;
    }
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    public java.util.List<? extends Neighbors.SquareOrBuilder> 
        getSquaresOrBuilderList() {
      return squares_;
    }
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    public int getSquaresCount() {
      return squares_.size();
    }
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    public Neighbors.Square getSquares(int index) {
      return squares_.get(index);
    }
    /**
     * <code>repeated .Square squares = 2;</code>
     */
    public Neighbors.SquareOrBuilder getSquaresOrBuilder(
        int index) {
      return squares_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < squares_.size(); i++) {
        output.writeMessage(2, squares_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      for (int i = 0; i < squares_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, squares_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Neighbors.Puzzle)) {
        return super.equals(obj);
      }
      Neighbors.Puzzle other = (Neighbors.Puzzle) obj;

      boolean result = true;
      result = result && (getSize()
          == other.getSize());
      result = result && getSquaresList()
          .equals(other.getSquaresList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getSquaresCount() > 0) {
        hash = (37 * hash) + SQUARES_FIELD_NUMBER;
        hash = (53 * hash) + getSquaresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Neighbors.Puzzle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Puzzle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Puzzle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Puzzle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Puzzle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Puzzle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Puzzle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Neighbors.Puzzle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Puzzle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Puzzle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Neighbors.Puzzle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Puzzle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Puzzle)
        Neighbors.PuzzleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Neighbors.internal_static_Puzzle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Neighbors.internal_static_Puzzle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Neighbors.Puzzle.class, Neighbors.Puzzle.Builder.class);
      }

      // Construct using Neighbors.Puzzle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSquaresFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        size_ = 0;

        if (squaresBuilder_ == null) {
          squares_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          squaresBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Neighbors.internal_static_Puzzle_descriptor;
      }

      public Neighbors.Puzzle getDefaultInstanceForType() {
        return Neighbors.Puzzle.getDefaultInstance();
      }

      public Neighbors.Puzzle build() {
        Neighbors.Puzzle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Neighbors.Puzzle buildPartial() {
        Neighbors.Puzzle result = new Neighbors.Puzzle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.size_ = size_;
        if (squaresBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            squares_ = java.util.Collections.unmodifiableList(squares_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.squares_ = squares_;
        } else {
          result.squares_ = squaresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Neighbors.Puzzle) {
          return mergeFrom((Neighbors.Puzzle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Neighbors.Puzzle other) {
        if (other == Neighbors.Puzzle.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (squaresBuilder_ == null) {
          if (!other.squares_.isEmpty()) {
            if (squares_.isEmpty()) {
              squares_ = other.squares_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSquaresIsMutable();
              squares_.addAll(other.squares_);
            }
            onChanged();
          }
        } else {
          if (!other.squares_.isEmpty()) {
            if (squaresBuilder_.isEmpty()) {
              squaresBuilder_.dispose();
              squaresBuilder_ = null;
              squares_ = other.squares_;
              bitField0_ = (bitField0_ & ~0x00000002);
              squaresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSquaresFieldBuilder() : null;
            } else {
              squaresBuilder_.addAllMessages(other.squares_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Neighbors.Puzzle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Neighbors.Puzzle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>optional int32 size = 1;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 1;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 1;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Neighbors.Square> squares_ =
        java.util.Collections.emptyList();
      private void ensureSquaresIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          squares_ = new java.util.ArrayList<Neighbors.Square>(squares_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Neighbors.Square, Neighbors.Square.Builder, Neighbors.SquareOrBuilder> squaresBuilder_;

      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public java.util.List<Neighbors.Square> getSquaresList() {
        if (squaresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(squares_);
        } else {
          return squaresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public int getSquaresCount() {
        if (squaresBuilder_ == null) {
          return squares_.size();
        } else {
          return squaresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Neighbors.Square getSquares(int index) {
        if (squaresBuilder_ == null) {
          return squares_.get(index);
        } else {
          return squaresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder setSquares(
          int index, Neighbors.Square value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.set(index, value);
          onChanged();
        } else {
          squaresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder setSquares(
          int index, Neighbors.Square.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.set(index, builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder addSquares(Neighbors.Square value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.add(value);
          onChanged();
        } else {
          squaresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder addSquares(
          int index, Neighbors.Square value) {
        if (squaresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSquaresIsMutable();
          squares_.add(index, value);
          onChanged();
        } else {
          squaresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder addSquares(
          Neighbors.Square.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.add(builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder addSquares(
          int index, Neighbors.Square.Builder builderForValue) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.add(index, builderForValue.build());
          onChanged();
        } else {
          squaresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder addAllSquares(
          java.lang.Iterable<? extends Neighbors.Square> values) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, squares_);
          onChanged();
        } else {
          squaresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder clearSquares() {
        if (squaresBuilder_ == null) {
          squares_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          squaresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Builder removeSquares(int index) {
        if (squaresBuilder_ == null) {
          ensureSquaresIsMutable();
          squares_.remove(index);
          onChanged();
        } else {
          squaresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Neighbors.Square.Builder getSquaresBuilder(
          int index) {
        return getSquaresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Neighbors.SquareOrBuilder getSquaresOrBuilder(
          int index) {
        if (squaresBuilder_ == null) {
          return squares_.get(index);  } else {
          return squaresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public java.util.List<? extends Neighbors.SquareOrBuilder> 
           getSquaresOrBuilderList() {
        if (squaresBuilder_ != null) {
          return squaresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(squares_);
        }
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Neighbors.Square.Builder addSquaresBuilder() {
        return getSquaresFieldBuilder().addBuilder(
            Neighbors.Square.getDefaultInstance());
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public Neighbors.Square.Builder addSquaresBuilder(
          int index) {
        return getSquaresFieldBuilder().addBuilder(
            index, Neighbors.Square.getDefaultInstance());
      }
      /**
       * <code>repeated .Square squares = 2;</code>
       */
      public java.util.List<Neighbors.Square.Builder> 
           getSquaresBuilderList() {
        return getSquaresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Neighbors.Square, Neighbors.Square.Builder, Neighbors.SquareOrBuilder> 
          getSquaresFieldBuilder() {
        if (squaresBuilder_ == null) {
          squaresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Neighbors.Square, Neighbors.Square.Builder, Neighbors.SquareOrBuilder>(
                  squares_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          squares_ = null;
        }
        return squaresBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Puzzle)
    }

    // @@protoc_insertion_point(class_scope:Puzzle)
    private static final Neighbors.Puzzle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Neighbors.Puzzle();
    }

    public static Neighbors.Puzzle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Puzzle>
        PARSER = new com.google.protobuf.AbstractParser<Puzzle>() {
      public Puzzle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Puzzle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Puzzle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Puzzle> getParserForType() {
      return PARSER;
    }

    public Neighbors.Puzzle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    java.util.List<Neighbors.Puzzle> 
        getPuzzlesList();
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    Neighbors.Puzzle getPuzzles(int index);
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    int getPuzzlesCount();
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    java.util.List<? extends Neighbors.PuzzleOrBuilder> 
        getPuzzlesOrBuilderList();
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    Neighbors.PuzzleOrBuilder getPuzzlesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      puzzles_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                puzzles_ = new java.util.ArrayList<Neighbors.Puzzle>();
                mutable_bitField0_ |= 0x00000001;
              }
              puzzles_.add(
                  input.readMessage(Neighbors.Puzzle.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          puzzles_ = java.util.Collections.unmodifiableList(puzzles_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Neighbors.internal_static_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Neighbors.internal_static_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Neighbors.Result.class, Neighbors.Result.Builder.class);
    }

    public static final int PUZZLES_FIELD_NUMBER = 1;
    private java.util.List<Neighbors.Puzzle> puzzles_;
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    public java.util.List<Neighbors.Puzzle> getPuzzlesList() {
      return puzzles_;
    }
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    public java.util.List<? extends Neighbors.PuzzleOrBuilder> 
        getPuzzlesOrBuilderList() {
      return puzzles_;
    }
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    public int getPuzzlesCount() {
      return puzzles_.size();
    }
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    public Neighbors.Puzzle getPuzzles(int index) {
      return puzzles_.get(index);
    }
    /**
     * <code>repeated .Puzzle puzzles = 1;</code>
     */
    public Neighbors.PuzzleOrBuilder getPuzzlesOrBuilder(
        int index) {
      return puzzles_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < puzzles_.size(); i++) {
        output.writeMessage(1, puzzles_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < puzzles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, puzzles_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Neighbors.Result)) {
        return super.equals(obj);
      }
      Neighbors.Result other = (Neighbors.Result) obj;

      boolean result = true;
      result = result && getPuzzlesList()
          .equals(other.getPuzzlesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPuzzlesCount() > 0) {
        hash = (37 * hash) + PUZZLES_FIELD_NUMBER;
        hash = (53 * hash) + getPuzzlesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Neighbors.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Neighbors.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Neighbors.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Neighbors.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Neighbors.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Neighbors.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Neighbors.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result)
        Neighbors.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Neighbors.internal_static_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Neighbors.internal_static_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Neighbors.Result.class, Neighbors.Result.Builder.class);
      }

      // Construct using Neighbors.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPuzzlesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (puzzlesBuilder_ == null) {
          puzzles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          puzzlesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Neighbors.internal_static_Result_descriptor;
      }

      public Neighbors.Result getDefaultInstanceForType() {
        return Neighbors.Result.getDefaultInstance();
      }

      public Neighbors.Result build() {
        Neighbors.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Neighbors.Result buildPartial() {
        Neighbors.Result result = new Neighbors.Result(this);
        int from_bitField0_ = bitField0_;
        if (puzzlesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            puzzles_ = java.util.Collections.unmodifiableList(puzzles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.puzzles_ = puzzles_;
        } else {
          result.puzzles_ = puzzlesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Neighbors.Result) {
          return mergeFrom((Neighbors.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Neighbors.Result other) {
        if (other == Neighbors.Result.getDefaultInstance()) return this;
        if (puzzlesBuilder_ == null) {
          if (!other.puzzles_.isEmpty()) {
            if (puzzles_.isEmpty()) {
              puzzles_ = other.puzzles_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePuzzlesIsMutable();
              puzzles_.addAll(other.puzzles_);
            }
            onChanged();
          }
        } else {
          if (!other.puzzles_.isEmpty()) {
            if (puzzlesBuilder_.isEmpty()) {
              puzzlesBuilder_.dispose();
              puzzlesBuilder_ = null;
              puzzles_ = other.puzzles_;
              bitField0_ = (bitField0_ & ~0x00000001);
              puzzlesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPuzzlesFieldBuilder() : null;
            } else {
              puzzlesBuilder_.addAllMessages(other.puzzles_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Neighbors.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Neighbors.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Neighbors.Puzzle> puzzles_ =
        java.util.Collections.emptyList();
      private void ensurePuzzlesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          puzzles_ = new java.util.ArrayList<Neighbors.Puzzle>(puzzles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Neighbors.Puzzle, Neighbors.Puzzle.Builder, Neighbors.PuzzleOrBuilder> puzzlesBuilder_;

      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public java.util.List<Neighbors.Puzzle> getPuzzlesList() {
        if (puzzlesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(puzzles_);
        } else {
          return puzzlesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public int getPuzzlesCount() {
        if (puzzlesBuilder_ == null) {
          return puzzles_.size();
        } else {
          return puzzlesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Neighbors.Puzzle getPuzzles(int index) {
        if (puzzlesBuilder_ == null) {
          return puzzles_.get(index);
        } else {
          return puzzlesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder setPuzzles(
          int index, Neighbors.Puzzle value) {
        if (puzzlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePuzzlesIsMutable();
          puzzles_.set(index, value);
          onChanged();
        } else {
          puzzlesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder setPuzzles(
          int index, Neighbors.Puzzle.Builder builderForValue) {
        if (puzzlesBuilder_ == null) {
          ensurePuzzlesIsMutable();
          puzzles_.set(index, builderForValue.build());
          onChanged();
        } else {
          puzzlesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder addPuzzles(Neighbors.Puzzle value) {
        if (puzzlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePuzzlesIsMutable();
          puzzles_.add(value);
          onChanged();
        } else {
          puzzlesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder addPuzzles(
          int index, Neighbors.Puzzle value) {
        if (puzzlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePuzzlesIsMutable();
          puzzles_.add(index, value);
          onChanged();
        } else {
          puzzlesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder addPuzzles(
          Neighbors.Puzzle.Builder builderForValue) {
        if (puzzlesBuilder_ == null) {
          ensurePuzzlesIsMutable();
          puzzles_.add(builderForValue.build());
          onChanged();
        } else {
          puzzlesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder addPuzzles(
          int index, Neighbors.Puzzle.Builder builderForValue) {
        if (puzzlesBuilder_ == null) {
          ensurePuzzlesIsMutable();
          puzzles_.add(index, builderForValue.build());
          onChanged();
        } else {
          puzzlesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder addAllPuzzles(
          java.lang.Iterable<? extends Neighbors.Puzzle> values) {
        if (puzzlesBuilder_ == null) {
          ensurePuzzlesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, puzzles_);
          onChanged();
        } else {
          puzzlesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder clearPuzzles() {
        if (puzzlesBuilder_ == null) {
          puzzles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          puzzlesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Builder removePuzzles(int index) {
        if (puzzlesBuilder_ == null) {
          ensurePuzzlesIsMutable();
          puzzles_.remove(index);
          onChanged();
        } else {
          puzzlesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Neighbors.Puzzle.Builder getPuzzlesBuilder(
          int index) {
        return getPuzzlesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Neighbors.PuzzleOrBuilder getPuzzlesOrBuilder(
          int index) {
        if (puzzlesBuilder_ == null) {
          return puzzles_.get(index);  } else {
          return puzzlesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public java.util.List<? extends Neighbors.PuzzleOrBuilder> 
           getPuzzlesOrBuilderList() {
        if (puzzlesBuilder_ != null) {
          return puzzlesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(puzzles_);
        }
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Neighbors.Puzzle.Builder addPuzzlesBuilder() {
        return getPuzzlesFieldBuilder().addBuilder(
            Neighbors.Puzzle.getDefaultInstance());
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public Neighbors.Puzzle.Builder addPuzzlesBuilder(
          int index) {
        return getPuzzlesFieldBuilder().addBuilder(
            index, Neighbors.Puzzle.getDefaultInstance());
      }
      /**
       * <code>repeated .Puzzle puzzles = 1;</code>
       */
      public java.util.List<Neighbors.Puzzle.Builder> 
           getPuzzlesBuilderList() {
        return getPuzzlesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Neighbors.Puzzle, Neighbors.Puzzle.Builder, Neighbors.PuzzleOrBuilder> 
          getPuzzlesFieldBuilder() {
        if (puzzlesBuilder_ == null) {
          puzzlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Neighbors.Puzzle, Neighbors.Puzzle.Builder, Neighbors.PuzzleOrBuilder>(
                  puzzles_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          puzzles_ = null;
        }
        return puzzlesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Result)
    }

    // @@protoc_insertion_point(class_scope:Result)
    private static final Neighbors.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Neighbors.Result();
    }

    public static Neighbors.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public Neighbors.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Square_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Square_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Puzzle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Puzzle_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017neighbors.proto\"\211\001\n\006Square\022\t\n\001x\030\001 \001(\005\022" +
      "\t\n\001y\030\002 \001(\005\022\016\n\006values\030\003 \003(\005\022\025\n\rneighbor_l" +
      "eft\030\004 \001(\010\022\026\n\016neighbor_right\030\005 \001(\010\022\023\n\013nei" +
      "ghbor_up\030\006 \001(\010\022\025\n\rneighbor_down\030\007 \001(\010\"0\n" +
      "\006Puzzle\022\014\n\004size\030\001 \001(\005\022\030\n\007squares\030\002 \003(\0132\007" +
      ".Square\"\"\n\006Result\022\030\n\007puzzles\030\001 \003(\0132\007.Puz" +
      "zleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Square_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Square_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Square_descriptor,
        new java.lang.String[] { "X", "Y", "Values", "NeighborLeft", "NeighborRight", "NeighborUp", "NeighborDown", });
    internal_static_Puzzle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Puzzle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Puzzle_descriptor,
        new java.lang.String[] { "Size", "Squares", });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new java.lang.String[] { "Puzzles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
