# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neighbors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neighbors.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fneighbors.proto\"\x89\x01\n\x06Square\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0e\n\x06values\x18\x03 \x03(\x05\x12\x15\n\rneighbor_left\x18\x04 \x01(\x08\x12\x16\n\x0eneighbor_right\x18\x05 \x01(\x08\x12\x13\n\x0bneighbor_up\x18\x06 \x01(\x08\x12\x15\n\rneighbor_down\x18\x07 \x01(\x08\"0\n\x06Puzzle\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x18\n\x07squares\x18\x02 \x03(\x0b\x32\x07.Square\"\"\n\x06Result\x12\x18\n\x07puzzles\x18\x01 \x03(\x0b\x32\x07.Puzzleb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SQUARE = _descriptor.Descriptor(
  name='Square',
  full_name='Square',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Square.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Square.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='Square.values', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_left', full_name='Square.neighbor_left', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_right', full_name='Square.neighbor_right', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_up', full_name='Square.neighbor_up', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_down', full_name='Square.neighbor_down', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=157,
)


_PUZZLE = _descriptor.Descriptor(
  name='Puzzle',
  full_name='Puzzle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='Puzzle.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='squares', full_name='Puzzle.squares', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=207,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='puzzles', full_name='Result.puzzles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=243,
)

_PUZZLE.fields_by_name['squares'].message_type = _SQUARE
_RESULT.fields_by_name['puzzles'].message_type = _PUZZLE
DESCRIPTOR.message_types_by_name['Square'] = _SQUARE
DESCRIPTOR.message_types_by_name['Puzzle'] = _PUZZLE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Square = _reflection.GeneratedProtocolMessageType('Square', (_message.Message,), dict(
  DESCRIPTOR = _SQUARE,
  __module__ = 'neighbors_pb2'
  # @@protoc_insertion_point(class_scope:Square)
  ))
_sym_db.RegisterMessage(Square)

Puzzle = _reflection.GeneratedProtocolMessageType('Puzzle', (_message.Message,), dict(
  DESCRIPTOR = _PUZZLE,
  __module__ = 'neighbors_pb2'
  # @@protoc_insertion_point(class_scope:Puzzle)
  ))
_sym_db.RegisterMessage(Puzzle)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'neighbors_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
